# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

def all_pods
  pod 'CTMediator'
  pod 'Masonry'
end

project = Xcodeproj::Project.open 'Example.xcodeproj'
project.targets.each do |t|
  target t.name do
    all_pods
  end
end
